# Generated by Django 2.2.6 on 2020-04-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200420_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
