# Generated by Django 2.2.6 on 2020-04-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/post/default-post.jpg', upload_to='blog/post'),
        ),
    ]
